language: go
sudo: false

go:
  - 1.3.3
  - 1.4.3
  - 1.5.3
  - 1.6

os:
  - linux
  - osx

install:
  - go get -t ./...
  - go get -u github.com/golang/lint/golint
  - go get -u golang.org/x/tools/cmd/goimports

script:
  - go vet ./...
  - diff <(goimports -d .) <(printf "")
  - diff <(golint ./...) <(printf "")
  - go test -v -cpu=2 ./...
  - go test -v -cpu=1,2,4 -short -race ./...
